### ISSUE TITLE
Building issue on the OracleLinux7

### ISSUE THREAD

**Issue by tingopingo** [Djelibeybi/build-subscription-manager#7]
Hi All,

I want to build subscription-manager package for Oracle Linux 7, 8 and 9. I have successfully able to build subscription-manager package for Oracle Linux 8 & 9.

But for Oracle Linux 7, multiple issues are being faced while running Dockerfile. So I modified it to resolve those issues, but even after that there are errors that I need your support to resolve.

 **My modified Dockerfile** 

FROM oraclelinux:7-slim

RUN echo "sslverify=0" >> /etc/yum.conf
RUN yum-config-manager --enable ol7_optional_latest
RUN yum -y install oracle-epel-release-el7 oracle-nodejs-release-el7 \
    && yum -y install @buildsys-build tito rpm-build rpm-sign nodejs npm which expect \
    && rm -rf /var/cache/yum \
    && npm config set strict-ssl false \
    && npm config set unsafe-perm true \
    && npm config set registry http://registry.npmjs.org/ \
    && npm install -g yarn \
    && rpmdev-setuptree

COPY scripts/* /
RUN chmod +x /my-build-rhsm.sh /rpm-sign.exp

CMD ["/my-build-rhsm.sh"]

**These are issues being faced. Complete output of "./build-rhsm-ol7.sh" is also attached.**

************************************
error: Bad file: /tmp/tito/rpmbuild-subscription-managereTU7Gq/SOURCES/subscription-manager-cockpit-1.24.51.tar.gz: No such file or directory

RPM build errors:
    Bad file: /tmp/tito/rpmbuild-subscription-managereTU7Gq/SOURCES/subscription-manager-cockpit-1.24.51.tar.gz: No such file or directory

ERROR: Error running command: rpmbuild  --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-subscription-managereTU7Gq" --define "_sourcedir /tmp/tito/rpmbuild-subscription-managereTU7Gq/SOURCES" --define "_builddir /tmp/tito/rpmbuild-subscription-managereTU7Gq/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito"  --define 'dist .el7' --nodeps -bs /tmp/tito/rpmbuild-subscription-managereTU7Gq/SOURCES/subscription-manager-1.24.51/subscription-manager.spec

Status code: 1

Command output: ['error: Bad file: /tmp/tito/rpmbuild-subscription-managereTU7Gq/SOURCES/subscription-manager-cockpit-1.24.51.tar.gz: No such file or directory', '', '', '', 'RPM build errors:', '    Bad file: /tmp/tito/rpmbuild-subscription-managereTU7Gq/SOURCES/subscription-manager-cockpit-1.24.51.tar.gz: No such file or directory']
*****************************************

Looking for your great help !!

Regards,
Faisal Naeem
[build-rhsm-ol7.sh - error n output.txt](https://github.com/Djelibeybi/build-subscription-manager/files/11818244/build-rhsm-ol7.sh.-.error.n.output.txt)

**Comment by Djelibeybi** [comment]
Fixed via #10
